
import MainLayoutComponent from "@/components/layout/main";
import type { Metadata } from "next";
import { auth } from '@/lib/auth';
import { headers } from 'next/headers';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <MainLayoutComponent>{children}</MainLayoutComponent>
    );
}
